### ISSUE TITLE
Memory Leak in 0.2.7

### ISSUE THREAD

**Issue by remeika** [martinlindhe/wmi_exporter#137]
**Note**: This is an initial bug report that does not contain nearly enough information to trace this issue. We are actively gathering telemetry about this issue, and will be updating this ticket.

We've observed when running WMI exporter 0.2.7, WMI exporter allocates 100s MB memory a small number of hosts, while the vast majority of instances allocate <10MB.

<img width="1440" alt="screen shot 2017-12-06 at 9 59 28 pm" src="https://user-images.githubusercontent.com/4956098/33696672-59bd259c-dad1-11e7-836e-d6211e16074f.png">

We are running the following configuration:

`wii_exporter.exe  -collectors.enabled cpu,cs,logical_disk,net,os,service,system`

On the hosts where we've seen this are [Nomad](https://nomadproject.io) agent nodes, that are running lots of application processes simultaneously. We have not observed high memory usage on hosts running a single application (example: DB clusters).

**Comment by martinlindhe** [comment]
> We've observed when running WMI exporter 0.2.7, WMI exporter allocates 100s MB memory a small number of hosts, while the vast majority of instances allocate <10MB.

I suspect you are monitoring the garbage collection taking place.

Please provide more details as to how this would be an issue with wmi_exporter

**Comment by martinlindhe** [comment]
Sorry, didn't mean to close the issue :-)

**Comment by martinlindhe** [comment]
We had a previous memory leak investigation which might be helpful to you, in https://github.com/martinlindhe/wmi_exporter/issues/77

**Comment by remeika** [comment]
Thats fair, the original chart doesn't show the behavior we are really concerned with. New Relic monitoring picked up the following example, where WMI Exporter used up 15GB of memory until it crashed. 

![screen shot 2017-12-07 at 10 52 02 am](https://user-images.githubusercontent.com/4956098/33724276-fb1f0b74-db3c-11e7-9c73-02f600376fb5.png)

**Comment by martinlindhe** [comment]
Okay, this is interesting.
You are only running the default collectors, a configuration we have profiled before.

Is the hosts running same version of Windows (and same patchlevel) by any chance?
There are countless threads about the wmi component leaking memory in Windows 7, Windows Server 2008, 2012R2 and possibly other editions. These issues may or may not be resolved by windows updates.

Since we are just querying the WMI, we don't control those parts. If this is the case, you may see similar behavior using other monitoring solutions that also rely on the WMI.

**Comment by remeika** [comment]
Yes, these VMs are part of an autoscale set, and thus are configured very consistently. Below is the patch version at time of the above incident:

```
> [System.Environment]::OSVersion.Version
Major  Minor  Build  Revision
-----  -----  -----  --------
10     0      14393  0

> (Get-WmiObject -class Win32_OperatingSystem).Caption
Microsoft Windows Server 2016 Datacenter
```

We do have other monitoring systems on these instances that exercise WMI, which have been running for many months without incident. A few other observations about this:

- It seems to occur on machines that have lots of work scheduled to run on them. 
- On one machine where this occurred, the WMI service was constantly stopping/starting on the system, i.e.

```Information	11/29/2017 5:26:00 PM	Service Control Manager	7036	None	The WMI Performance Adapter service entered the running state.
Information	11/29/2017 5:25:59 PM	Service Control Manager	7036	None	The WMI Performance Adapter service entered the stopped state.
Information	11/29/2017 5:25:59 PM	Service Control Manager	7036	None	The WMI Performance Adapter service entered the running state.
Information	11/29/2017 5:25:58 PM	Service Control Manager	7036	None	The WMI Performance Adapter service entered the stopped state.```

We have hundreds of identically configured machines that were running the exporter, and a small percentage experienced a leak like this.

**Comment by BertHartm** [comment]
I've been taking over from @remeika in looking at these problematic exporters / machines.

From looking at behavior of the exporter and memory dumps, I think the issue may have to do with WMI returning more slowly than we are scraping, which results in many simultaneous scrapes going on since the wmi_exporter keeps processing even after the scrape_timeout. I'm not sure what the memory requirements are per scrape, but if it's significant, that could cause some issues. I assume there's a leak in combination that's getting us to 15GB over the course of weeks, but we're now proactively restarting to prevent that.

Looking at the scrape information (sometimes pulling it out of memory), I'm seeing each WMI query taking up to 100s in some cases, which is far longer than we wait for results. Giving some extra grace for the scrapes, we also see longish scrapes on some machine (e.g. on the order of 1minute to return results) with recovery (sub 1s) after some time.

The machines that are having problems have many (10-100) processes polling WMI for process level information for their own purposes. I think this may contribute to the WMI slowness, though those processes themselves seem to keep returning data in a fairly normal manner.

Has there been any thought around preferred behavior in the case of slow WMI queries? I'm looking into options around:
a) timeouts on the queries (configured relative to the scrape_timeout)
b) returning cached results if WMI is slow
c) intentionally not returning results if WMI is slow
d) seeing what the performance implications of using a Refresher ( https://msdn.microsoft.com/en-us/library/aa393838(v=vs.85).aspx ) instead of re-querying on every scrape.

**Comment by brian-brazil** [comment]
> a) timeouts on the queries (configured relative to the scrape_timeout)

Prometheus passes down the timeout in a header.

> returning cached results if WMI is slow

Caching is to be avoided.

> intentionally not returning results if WMI is slow

The query is already failing. This should be an all or nothing thing.

**Comment by carlpett** [comment]
We've implemented timeouts since a few releases ago, which should have solved the problem. Please open a new issue if it is still happening!
