### ISSUE TITLE
MSMQ collector

### ISSUE THREAD

**Issue by VR6Pete** [martinlindhe/wmi_exporter#153]
Hi There, 

Within the environment I wish to monitor we use MSMQ for some legacy applications.

I understand that this is exposed via WMI (Win32_PerfRawData_MSMQ, Win32_PerfFormattedData_MSMQ_MSMQService etc...) - I am wondering if this can be added as a collector to WMI exporter or if there is another method exists that will get me up and running?

Thanks.

Pete

**Comment by carlpett** [comment]
Hi!
Yes, this would fit in perfectly as a collector to WMI exporter! We have [a script](https://github.com/martinlindhe/wmi_exporter/tree/master/tools/collector-generator) which can be used to generate most of the code necessary. Are you familiar with Go programming? There is often some amount of tuning required to get good results (WMI is not quite as uniform as one could hope, so it is hard to generate "perfect" code, unfortunately).

**Comment by VR6Pete** [comment]
Hi Carlpett. 

I'm afraid I am not familiar with Go programming. If its any help I am looking to get current queue sizes and identify if a queue has become stuck / not processing.

**Comment by VR6Pete** [comment]
Hi there. 

Any further advice with this ? When will be the next release with this included?

Many thanks

Pete

**Comment by carlpett** [comment]
Hi @VR6Pete,
Please understand that this is a project being developed in our spare time. Implementing this will not only require some coding, but also a non-trivial amount of time in setting up the required services so that it is testable.
As it stands, I am unfortunately not able to give any promises regarding when anyone will have time to implement it.

**Comment by carlpett** [comment]
I know some projects have methods for letting those who are not able to contribute directly instead sponsor the requisite development time. Perhaps we should look into that, since the overlap between operators of Windows systems and Go programmers is quite small.
As a very non-formal poll, would that sort of "feature request purchase" be interesting to you/your employer, @VR6Pete?

**Comment by martinlindhe** [comment]
Good call, @carlpett

**Comment by VR6Pete** [comment]
depends what sort of costs we are looking at :)

**Comment by VR6Pete** [comment]
Any update on the above? Keen to explore options here?

**Comment by carlpett** [comment]
@VR6Pete Sorry for the slow response, I've been out on a business trip this week.
We could arrange something, I'm sure. Do you have some contact details?
Also, a basic collector was actually contributed earlier this morning: [#159](https://github.com/martinlindhe/wmi_exporter/pull/159). Does this fulfill your needs?

**Comment by VR6Pete** [comment]
I think that is a good starter for 10 - Do you know when a new MSI will be packaged?

**Comment by carlpett** [comment]
Great! I'm tagging the release now, msi:s should be available in a few minutes

**Comment by VR6Pete** [comment]
Fab. Updated and working great!
