### ISSUE TITLE
[Question] wmi_logical_disk_free_bytes - predict_linear?

### ISSUE THREAD

**Issue by VR6Pete** [martinlindhe/wmi_exporter#161]
Hi there,

I am trying to apply the method from;

https://www.robustperception.io/reduce-noise-from-disk-space-alerts/

but using data from wmi exporter as per the below but just a message "No datapoints found."

predict_linear(wmi_logical_disk_free_bytes{instance="xxxxx"}[1h], 4 * 3600) < 0

Tried a few variations but none appear to be working. Any clues as to where I am going wrong? 

Thanks.

Pete

**Comment by carlpett** [comment]
Hi,
I've successfully used that pattern myself, so that should definitely work. My guess is that you actually don't have any disks that are about to run out of space? Try removing the `< 0` part, and you should get the predicted free bytes in four hours. Does that work?

(Tip: You'll probably get faster help on the prometheus-users maillist :) )

**Comment by VR6Pete** [comment]
Ahha. Was a tough day 😂 and have now discovered the user group thanks as always
