### ISSUE TITLE
How do I uninstall & stop?

### ISSUE THREAD

**Issue by FrozenBeard** [martinlindhe/wmi_exporter#208]
I installed the 32bit version on my windows server 2016, I have no idea where its been installed, and I have no idea how to stop it or remove it.

**Comment by carlpett** [comment]
Hi @FrozenBeard!
The installation directory is `C:\Program Files\wmi_exporter`. It will install as a service, so to stop it you could use the normal Administrative Tools > Services and stop it there.
In order to uninstall, you'd go to Add/remove program and do it from there.

Does this answer your question?
