### ISSUE TITLE
wmi_process_working_set Metric missing

### ISSUE THREAD

**Issue by krdineshbny** [martinlindhe/wmi_exporter#224]
Hi team, 
Iam using wmi exporter version 0.3.3
I am able to get most of the node related metrics with this exporter.
We are in the process of setting up alerts for process,cpu,memory,disk et.,
To calculate the memory usage for each process we are planning to use
**wmi_process_working_set** metrics
But this metric is missing in the exporter which i am testing in my machine and few other servers.
Am i missing something when i do the msi installation.
Also is there anyother metric/ combination of metrics which can provide us the memory usage of each process?

**Comment by carlpett** [comment]
Hi @krdineshbny,
Did you enable the `process` collector? It is not enabled by default.

**Comment by krdineshbny** [comment]
@carlpett  thanks for the response
how to enable collector to get all the metrics
I was under the assumption that running the exporter will expose all metrics and the using 
--collectors.enabled
is only to for limiting the amount of metrics to a specific process/service.
So in the command prompt i should run like this?
.\wmi_exporter.exe --collectors.enabled

**Comment by carlpett** [comment]
All collectors are not enabled by default, since some of them only make sense on certain installations (the IIS collector on servers without IIS installed, for example, or the vmware one on machines that are not running on a VMWare hypervisor). See [this table](https://github.com/martinlindhe/wmi_exporter#collectors) in the README for details on what is enabled by default.

To select which collectors to enable, you pass them as a comma-separated list to that flag, so `.\wmi_exporter.exe --collectors.enabled cpu,os` to only use the cpu and os collectors. In order to use the default set and add some more ones, you can use the special placeholder `[defaults]`, so `.\wmi_exporter.exe --collectors.enabled [defaults],process` to enable all the default ones and also turn on the process collector.

**Comment by krdineshbny** [comment]
Also, what are the list of collectors available apart from
cpu,cs,logical_disk,net,os,service,system and textfile

**Comment by krdineshbny** [comment]
@carlpett  Thank you
This clears my query will try using [defaults] along with the other collectors depending on the type of windows server

**Comment by carlpett** [comment]
Great!
