### ISSUE TITLE
Errors on event viewer

### ISSUE THREAD

**Issue by homayoonhosseini** [martinlindhe/wmi_exporter#239]
I got this error on event viewer:
The description for Event ID 102 from source wmi_exporter cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer.

If the event originated on another computer, the display information had to be saved with the event.

The following information was included with the event: 

Error reading textfile collector directory "C:\\Program Files\\wmi_exporter\\textfile_inputs": open C:\Program Files\wmi_exporter\textfile_inputs: The system cannot find the path specified.

**Comment by carlpett** [comment]
Hi @homayoonhosseini,
The first part there is not actually an error (see #22). The latter part just says that it cannot find the directory for the `textfile` collector inputs. Are you using the textfile collector? Otherwise you can ignore this.
However, this directory _should_ be created by the installer. What version of the exporter are you running?

**Comment by carlpett** [comment]
#22 is fixed.
