### ISSUE TITLE
Firewall settings changed

### ISSUE THREAD

**Issue by Szadegan** [martinlindhe/wmi_exporter#330]
I installed 0.6 version on a Windows server 2012 R2 Standard edition and it automatically changed my Firewall settings So I could not connect to the Machine with RDP :( 
Did I miss anything during the installation process or its just like that?

**Comment by carlpett** [comment]
Hi @Szadegan,
No, this should not happen, and I haven't heard of it before. During installation, if the firewall is enabled, we do add a firewall exception for the port we use, but we definitely don't disable RDP.
Could you explain your setup a bit more? Did you have the firewall completely disabled before installing, or was it enabled but some config changed to block RDP?

**Comment by Szadegan** [comment]
The firewall was enabled during installation and after the installation the RDP settings were changed

**Comment by carlpett** [comment]
Very strange! The only thing we do ([here](https://github.com/martinlindhe/wmi_exporter/blob/master/installer/wmi_exporter.wxs#L46)) is adding an exception for our port, as I mentioned. This all happens using built-in things in the Windows Installer toolkit, rather than custom code written by us.
Is there anything particular with your setup? Is this cloud-hosted or local? Do you have the possibility to test the installation again, with logging enabled (by running `msiexec /l*v "log.log" /i "path-to-wmi_exporter.msi"`)?

**Comment by Szadegan** [comment]
Its a VM hosted on a local hyper-v. Sure I will test it again and let you know :)

**Comment by Szadegan** [comment]
I have tried it again and it works without any problems. Might have been something else which I have tested at the same time. 
Thanks
