### ISSUE TITLE
Process Monitor - How to enable specific metrics only

### ISSUE THREAD

**Issue by nevesing** [martinlindhe/wmi_exporter#451]
I am trying to monitor all the processes running on few windows servers using '**process collector**'. Question is how do I capture/enable '**wmi_process_cpu_time_total**' metric only? Is this possible?

**Comment by carlpett** [comment]
Hi @nevesing,
You cannot do this within the exporter itself, instead this is something you configure in your Prometheus server using [`relabel_config`](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#relabel_config). From memory, you'll likely want to set `action: keep`, `source_labels: [__name__]` and `regex: wmi_process_cpu_time_total`.

**Comment by nevesing** [comment]
Hi @carlpett,

I see. But the exporter will still collect those metrics and i thought to avoid extra foot print as it might impact resources (cpu/memory) on that server by collecting the metrics which I dont need.

**Comment by carlpett** [comment]
I understand. However, we do not offer a way to selectively disable metrics, not least because the configuration required to support this would become very complex.
I would encourage you to do careful measurements before assuming that this makes a big difference, however. To me it seems equally likely that the majority of the cost is just from executing any query at all, and the volume of returned data is a rather small part. But again, measure first, in case you determine this is a problem.

**Comment by nevesing** [comment]
Will do. Thank you.
