### ISSUE TITLE
N/A for all CPU metrics

### ISSUE THREAD

**Issue by windinahead** [martinlindhe/wmi_exporter#509]
Hi, colleagues!
I'm a newbie in Prometheus and Grafana and need your  help: I have several panels in dashboard for CPU. All of them show N/A, but regex for them looks correct: for example for CPU Usage by mode
sum by (mode) (irate(wmi_cpu_time_total{job=~"$server.*"}[$interval])) and No Data on the graph. 

> Variables are: 
> $server | label_values(wmi_mssql_collector_duration_seconds, job)
> $dbinstance | label_values(wmi_mssql_genstats_logical_connections{job=~"$server.*"}, exported_instance)

Could you tell me what's wrong?
Thank you in advance!

**Comment by carlpett** [comment]
Hi @windinahead,
There are no obvious errors in the query or variables (although using the `job` label to hold instances is a bit unusual, normally you'd use the `instance` label). I'd start with reducing complexity one step at a time and see where things go wrong. For example, remove the filters in the query and verify that you get data. Or hardcode an interval like `5m` instead of using the variable.

**Comment by windinahead** [comment]
Thank you, @carlpett!
You're genius! I changed the $interval from 60s to 2m and it works!

**Comment by carlpett** [comment]
Ah, great! That is something to keep in mind - you'll need to keep the interval long enough to cover *at least* two data points, so it needs to be scaled for your scrape interval. Best practice is considered to have 4x your scrape interval as the minimum, to allow for some failed scrapes.
But nice that it works :tada:
