### ISSUE TITLE
Service monitoring uses too many timeseries

### ISSUE THREAD

**Issue by basroovers** [martinlindhe/wmi_exporter#515]
I just started using the service collector but it's already ranked as the highest in cardinality.

![image](https://user-images.githubusercontent.com/2011325/81226722-964df780-8feb-11ea-9b1b-e6471b7da13e.png)

This because each Windows service takes 8 time series just for the state alone.

```
wmi_service_state{name="axinstsv",state="continue pending"} 0
wmi_service_state{name="axinstsv",state="pause pending"} 0
wmi_service_state{name="axinstsv",state="paused"} 0
wmi_service_state{name="axinstsv",state="running"} 0
wmi_service_state{name="axinstsv",state="start pending"} 0
wmi_service_state{name="axinstsv",state="stop pending"} 0
wmi_service_state{name="axinstsv",state="stopped"} 1
wmi_service_state{name="axinstsv",state="unknown"} 0
```

Same thing for the start mode:

```
wmi_service_start_mode{name="winrm",start_mode="auto"} 1
wmi_service_start_mode{name="winrm",start_mode="boot"} 0
wmi_service_start_mode{name="winrm",start_mode="disabled"} 0
wmi_service_start_mode{name="winrm",start_mode="manual"} 0
wmi_service_start_mode{name="winrm",start_mode="system"} 0
```

And finally the largest one:
```
wmi_service_status{name="winrm",status="degraded"} 0
wmi_service_status{name="winrm",status="error"} 0
wmi_service_status{name="winrm",status="lost comm"} 0
wmi_service_status{name="winrm",status="no contact"} 0
wmi_service_status{name="winrm",status="nonrecover"} 0
wmi_service_status{name="winrm",status="ok"} 1
wmi_service_status{name="winrm",status="pred fail"} 0
wmi_service_status{name="winrm",status="service"} 0
wmi_service_status{name="winrm",status="starting"} 0
wmi_service_status{name="winrm",status="stopping"} 0
wmi_service_status{name="winrm",status="stressed"} 0
wmi_service_status{name="winrm",status="unknown"} 0
```

**Proposal**
This could be reduced to 3 time series per Windows service by giving each state a different number.
Total reduction of 22 time series per Window service. With and average of 200 Windows services this would reduce the total amount of time series with 4000 time series. Seems worth the trouble to me.

Start mode:
0 == auto
1 == boot
2 == disabled
3 == manual
4 == system

E.g. this service would be set to manual
```
wmi_service_start_mode{name="winrm"} 3
```

Using the above proposed method would also simplify an alert query where I would like to see all Windows services that are set to automatic but are not running.

```
wmi_service_state == 0 and wmi_service_startup_mode == 0
```

Is there any reasoning behind this that I'm missing?

**Comment by carlpett** [comment]
Hi @basroovers,
Thanks for the analysis! And yes, it is rather heavy, and we currently log a warning about this if the service list isn't given a filter to keep this number down. More of a workaround than a solution, granted.
As for reasoning, the "0/1 gauge" pattern is quite common in Promtheus, and I believe this type of magic numbers are considered worse, in general. It's fair to question if this is the right choice here of course, as the impact is fairly large, as you point out.

@SuperQ, the systemd collector on the node_exporter has a similar structure (and yields ~1000 series per node without tuning on my machines), has there been any discussion on this type of format there, and what arguments presented?

**Comment by SuperQ** [comment]
Prometheus doesn't have any kind of first-class support for ENUMs. Doing queries against integers can be much more difficult. So the common pattern in Prometheus is to map ENUM values to labels and use a bit-mask approach.

For example, this is exactly how we translate SNMP ENUMs into Prometheus. You get the int value by default, but can select `EnumAsStateSet` or `EnumAsInfo`. The state set is the same as we're doing here. Each value gets a boolean label. This works well because you can much more easily do joins, don't have to worry about absent metrics. Info-style will only include the label value and a 1 value.

Info is fine for things that aren't meant to change. Like a device interface type. But state sets/bitmasks work better where you want to track the changing state over time.

I don't have a simple, quick document about why we prefer to use state sets over ENUM int values or having just the current state as a label. But it is the preferred method.

**Comment by SuperQ** [comment]
Another thing to note, with the labels as-is, the indexing of series is pretty optimal. The full combination of metrics for 200 nodes above is pretty trivial to handle with Prometheus. It's far more efficient for that tiny, under 20k series, setup. It might seem like a lot for other monitoring systems. But it's efficiently handled by Prometheus.

**Comment by basroovers** [comment]
Thanks for explaining a bit of back story here. Very insightful.

May I just point that it's not only performance which might suffer but also the amount of storage needed when using the service collector for > 200 nodes (which I plan to do).

You could by the way still have the enum value as a label:
```
wmi_service_start_mode{name="winrm",state="running"} 3
```

**Comment by SuperQ** [comment]
That's still not any better, because state changes cause the series to appear and disappear.

For the storage side, constant-value series are handled by the best-case compression. This is extremely compressed. IIRC it's something on the order of 0.3 bytes/sample. And we're considering additional optimizations.  The example 15k series is something like 25MiB/day of data scraped at 15s intervals. It's mostly an indexing problem, not a series storage problem.

Prometheus typical compression for normal metrics is still around 1.3 bytes/sample. So even with this low amount of compression, 15k series is still around 110MiB/day.

Typically we start to get concerned with Prometheus series cardinality when you hit around 10 million series on a server.

Here's an example of a normal operating Prometheus server:

![image](https://user-images.githubusercontent.com/1320667/81384589-2dad6a80-9112-11ea-9bdd-f34062c1908e.png)

These numbers are not concerning.

**Comment by basroovers** [comment]
Thanks for explaining. I'll close the issue.
