### ISSUE TITLE
[featurerequest] Per-process information

### ISSUE THREAD

**Issue by seanhoughton** [martinlindhe/wmi_exporter#52]
It would be useful to get a per-process (i.e. image name) value for each metric.

**Comment by waqark3389** [comment]
+1

**Comment by carlpett** [comment]
Sorry, missed this one! This is probably not going to happen dynamically, however, since it will likely result in a very high number of metrics. As an example, on my laptop I currently have several hundred processes, many with names dependent on startup-order, etc. Process ids have a similar problem in that they are not possible to correlate over process restarts, etc. 
One possibility would be to allow adding a list of processes that you are interested in and get just those, but I'm not sure if that wouldn't live better in a separate exporter?

**Comment by waqark3389** [comment]
@carlpett @seanhoughton Since checking this exporter out I have started to use scollector exporter. 
https://github.com/tgulacsi/prometheus_scollector

Its pretty simple to set up, you need to stick this on the windoze machine: http://bosun.org/scollector/ and the exporter itself can run anywhere, just point scollector at the exporter. 
It has a regex match for name of process you would like to monitor. 
Create a file called scollector.toml with e.g.:

[[Process]]
  Name = "^randomProcessName."

So for anything process related on Dos* I have started using scollector and everything else is using the wmi_exporter :) 

@carlpett If you are going to create a seperate exporter that would be even better as it removes the dependency for scollector. Because I really like your wmi_exporter, very efficient and tiny footprint.

**Comment by carlpett** [comment]
This is fixed in #79!

**Comment by bbigras** [comment]
Is there a simple way to use the `collector.process.processes-where` flag or do I need to create the service myself? I don't seem able to add arguments to the wmi-exporter service.

**Comment by carlpett** [comment]
Ah, no, that is something we did not think about. Sorry about that. If you know your way around `sc.exe`, that is probably the easiest way short-term, or going into regedit and changing the parameters there.
We'll have to add some "other options" parameter to the msi, I guess.
