### ISSUE TITLE
Feature: IIS metrics

### ISSUE THREAD

**Issue by carlpett** [martinlindhe/wmi_exporter#9]

**Comment by carlpett** [comment]
I'm working on this via the Win32_PerfRawData_W3SVC_WebService class. There are _a lot_ of different sources for IIS in perfmon however, so maybe there are other classes which are better suited?

**Comment by martinlindhe** [comment]
Very nice! I was thinking earlier today about other Windows metrics, in particular SQL Server stuff (which I will need to investigate sooner or later anyway), and if they are exposed in WMI, would they fit this collector, or as separate project.

Assuming they are available as WMI, I guess they can fit in this project.

In any case I think it would make sense for the user to be able to configure the exported collectors, since in this case IIS might not be useful as enabled by default for all users.

**Comment by carlpett** [comment]
Yup, I'm thinking we should just copy the structure used in `node_exporter`, with a flag for `enabled-collectors`

**Comment by martinlindhe** [comment]
Agreed. Perhaps the "perf" and "os" ones should be exported by default.

**Comment by brian-brazil** [comment]
IIS is a network service, so should have its own exporter (unless you're going to go down the JMX exporter route).

**Comment by carlpett** [comment]
From the discussions in #5:
>What I'd see happening for IIS/SQL is that you'd run the WMI exporter but with different flags just pulling in IIS/SQL metrics.
@brian-brazil With users running multiple exporters for servers with multiple databases/webapps, much like for other exporters, I assume? We'll need to test that at larger scales, I think. I've seen non-negligible performance impact from running many WMI queries (the current approach would just be one query for all say 20 sites, rather than 20 queries for one site each).

**Comment by martinlindhe** [comment]
This is related to #12
